const PERMISSION_CATEGORIES = {
    "Sản phẩm": ["viewProduct", "manageProduct"],
    "Loại sản phẩm": ["viewProductType", "manageProductType"],
    "Đối tác": ["viewPartner", "managePartner"],
    "Kho": ["viewWarehouse", "manageWarehouse"],
    "Nguyên vật liệu": ["viewMaterial", "manageMaterial"],
    "Loại nguyên vật liệu": ["viewMaterialType", "manageMaterialType"],
    "Đơn hàng": ["viewSaleOrder", "manageSaleOrder"],
    "Yêu cầu mua": ["viewPurchaseRequest", "managePurchaseRequest"],
    "Đơn mua": ["viewPurchaseOrder", "managePurchaseOrder"],
    "Đơn vị": ["viewUnit", "manageUnit"],
    "Báo cáo": ["viewReport"],
    "Phiếu nhập kho": ["viewReceiptNote", "manageReceiptNote"],
    "Phiếu xuất kho": ["viewIssueNote", "manageIssueNote"],
    "Duyệt yêu cầu mua": ["acceptPurchaseRequest"],
  };
  
  const PERMISSION_LABELS = {
    viewProduct: "Xem",
    manageProduct: "Quản lý",
    viewProductType: "Xem",
    manageProductType: "Quản lý",
    viewPartner: "Xem",
    managePartner: "Quản lý",
    viewWarehouse: "Xem",
    manageWarehouse: "Quản lý",
    viewMaterial: "Xem",
    manageMaterial: "Quản lý",
    viewMaterialType: "Xem",
    manageMaterialType: "Quản lý",
    viewSaleOrder: "Xem",
    manageSaleOrder: "Quản lý",
    viewPurchaseRequest: "Xem",
    managePurchaseRequest: "Quản lý",
    viewPurchaseOrder: "Xem",
    managePurchaseOrder: "Quản lý",
    viewUnit: "Xem",
    manageUnit: "Quản lý",
    viewReport: "Xem",
    viewReceiptNote: "Xem",
    manageReceiptNote: "Quản lý",
    viewIssueNote: "Xem",
    manageIssueNote: "Quản lý",
    acceptPurchaseRequest: "Duyệt",
  };
  
  export { PERMISSION_CATEGORIES, PERMISSION_LABELS };