spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unistock?createDatabaseIfNotExist=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    allowed-origins: "http://localhost:3000,http://your-production-url.com"
  file:
    images:
      location: public/images/
jwt:
  secret: "YWJjZGVmZ2hpamtsbW5vcHFyc3R1d2V4eXoqc29uZ2hhaWNr"