spring:
  profiles:
    active: dev

  datasource:
    url: ${PROFILE_URL} --placeholder
    username: ${PROFILE_USERNAME}
    password: ${PROFILE_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: validate
#      ddl-auto: create
    ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false  # ❌ Tắt cache cấp 2
          use_query_cache: false
